resources:
- name: music-repo
  type: git
  source:
    uri: git@github.com:mwright-pivotal/concourse-spring-music.git
    branch: master
    private_key: {{music_private_key}}
    username: mwright-pivotal
    password: newuser1

- name: version
  type: semver
  source:
    endpoint: {{s3-endpoint}}
    bucket: music-pipeline-artifacts
    key: current-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    initial_version: 1.0.0

- name: music-release
  type: s3
  source:
    bucket: music-pipeline-artifacts
    regexp: spring-music-(.*).war
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    endpoint: {{s3-endpoint}}

jobs:
- name: unit
  plan:
  - get: music-repo
    trigger: true
  - task: unit
    file: music-repo/ci/tasks/unit.yml

- name: build-binary
  serial: true
  plan:
  - get: music-repo
    passed: [unit]
    trigger: true
  - get: version
    params: {bump: patch}
  - task: build-artifact
    file: music-repo/ci/tasks/build-artifact.yml
    timeout: 5m
  - put: music-release
    params: {file: build-output/spring-music-*.war}
  - put: music-repo
    params:
      repository: music-repo
      tag: version/number
  - put: version
    params: {file: version/number}

- name: acceptance-tests
  plan:
  - aggregate:
    - get: music-release
      passed: [build-binary]
      trigger: true
    - get: music-repo
      passed: [build-binary]
      trigger: true
  - task: deploy-to-cats
    file: music-repo/ci/tasks/cf-deployment.yml
    config:
      params:
        API_ENDPOINT: api.cf.wrightcode.net
        USERNAME: mwright@pivotal.io
        PASSWORD: p1v0tal
        ORG: wright-org
        SPACE: CI
        HOST: music-cats
  - task: cats
    file: music-repo/ci/tasks/cats.yml
    config:
      params:
        MUSIC_URL: http://music-cats.cf.wrightcode.net

- name: promote-to-uat
  plan:
  - aggregate:
    - get: music-release
      passed: [acceptance-tests]
      trigger: true
    - get: music-repo
      passed: [acceptance-tests]
      trigger: true
  - task: deploy-to-uat
    file: music-repo/ci/tasks/cf-deployment.yml
    config:
      params:
        API_ENDPOINT: api.cf.wrightcode.net
        USERNAME: mwright@pivotal.io
        PASSWORD: p1v0tal
        ORG: wright-org
        SPACE: uat
        HOST: music-uat

- name: manual-deploy-to-prod
  serial: true
  plan:
  - aggregate:
    - get: music-release
      passed: [promote-to-uat]
    - get: music-repo
      passed: [promote-to-uat]
  - task: deploy-to-prod
    file: music-repo/ci/tasks/cf-deployment.yml
    config:
      params:
        API_ENDPOINT: api.cf.wrightcode.et
        USERNAME: mwright@pivotal.io
        PASSWORD: p1v0tal
        ORG: wright-org
        SPACE: prod
        HOST: music
